CREATE TABLE brands (
  id SERIAL PRIMARY KEY,
  brand TEXT UNIQUE NOT NULL
);

INSERT INTO brands
VALUES
(DEFAULT, 'Westbrae'),
(DEFAULT, 'Wai Wai'),
(DEFAULT, 'Vifon'),
(DEFAULT, 'Ve Wong'),
(DEFAULT, 'Tung-I'),
(DEFAULT, 'Sutah'),
(DEFAULT, 'Smack'),
(DEFAULT, 'Six Fortune'),
(DEFAULT, 'Sapporo Ichiban'),
(DEFAULT, 'Samyang'),
(DEFAULT, 'Quickchow'),
(DEFAULT, 'Ottogi'),
(DEFAULT, 'Nongshim'),
(DEFAULT, 'Nissin'),
(DEFAULT, 'Mee Jang'),
(DEFAULT, 'Myojo'),
(DEFAULT, 'Koka'),
(DEFAULT, 'Maruchan'),
(DEFAULT, 'Mama'),
(DEFAULT, 'Lucky Me!'),
(DEFAULT, 'Little Cook'),
(DEFAULT, 'Kim Ve Wong'),
(DEFAULT, 'Indomie'),
(DEFAULT, 'Hua Feng Noodle Expert'),
(DEFAULT, 'Doll'),
(DEFAULT, 'Maggi'),
(DEFAULT, 'Wei Lih'),
(DEFAULT, 'Baijia'),
(DEFAULT, 'Unif / Tung-I'),
(DEFAULT, 'Paldo'),
(DEFAULT, 'Unif'),
(DEFAULT, 'Long Kow'),
(DEFAULT, 'Binh Tay'),
(DEFAULT, 'Fashion Food'),
(DEFAULT, 'Payless'),
(DEFAULT, 'Saigon Ve Wong'),
(DEFAULT, 'GreeNoodle'),
(DEFAULT, 'Teriyaki Time'),
(DEFAULT, 'Shirakiku'),
(DEFAULT, 'Global Inspiration'),
(DEFAULT, 'Kamfen'),
(DEFAULT, 'Sakurai'),
(DEFAULT, 'Higashi'),
(DEFAULT, 'Chorip Dong'),
(DEFAULT, 'Wu Mu'),
(DEFAULT, 'Koyo'),
(DEFAULT, 'JFC'),
(DEFAULT, 'Boss'),
(DEFAULT, 'Rhee Bros Assi'),
(DEFAULT, 'Bon Go Jang'),
(DEFAULT, 'Sao Tao'),
(DEFAULT, 'Rocket Brand'),
(DEFAULT, 'Vina Acecook'),
(DEFAULT, 'Sanyo Foods'),
(DEFAULT, 'Fu Chang Chinese Noodle Company'),
(DEFAULT, 'Fashion Foods'),
(DEFAULT, 'Fortune'),
(DEFAULT, 'Royal Umbrella'),
(DEFAULT, 'Tiger'),
(DEFAULT, 'Tablemark'),
(DEFAULT, 'Dragonfly'),
(DEFAULT, 'Tradition'),
(DEFAULT, 'Gomex'),
(DEFAULT, 'Sunlee'),
(DEFAULT, 'Goku Uma'),
(DEFAULT, 'Super Bihun'),
(DEFAULT, 'Sunny Maid'),
(DEFAULT, 'Tayho'),
(DEFAULT, 'Knorr'),
(DEFAULT, 'Fuku'),
(DEFAULT, 'Noodle Time'),
(DEFAULT, 'Sau Tao'),
(DEFAULT, 'US Canning'),
(DEFAULT, 'Menraku'),
(DEFAULT, 'Ibumie'),
(DEFAULT, 'Souper'),
(DEFAULT, 'iNoodle'),
(DEFAULT, 'Q'),
(DEFAULT, 'Chikara'),
(DEFAULT, 'Mi Sedaap'),
(DEFAULT, 'Mr. Udon'),
(DEFAULT, 'Gefen'),
(DEFAULT, 'Thai Kitchen'),
(DEFAULT, 'Annie Chun''s'),
(DEFAULT, 'Vedan'),
(DEFAULT, 'Itomen'),
(DEFAULT, 'Kailo'),
(DEFAULT, 'JML'),
(DEFAULT, 'Foodmon'),
(DEFAULT, 'Noah Foods'),
(DEFAULT, 'Pulmuone'),
(DEFAULT, 'Snapdragon'),
(DEFAULT, 'Hsin Tung Yang'),
(DEFAULT, 'Mexi-Ramen'),
(DEFAULT, 'Wang'),
(DEFAULT, 'Nan Hsing'),
(DEFAULT, 'Unox'),
(DEFAULT, 'Yum Yum'),
(DEFAULT, 'Golden Wheat'),
(DEFAULT, 'Pot Noodle'),
(DEFAULT, 'Batchelors'),
(DEFAULT, 'Sahmyook'),
(DEFAULT, 'Uni-President'),
(DEFAULT, 'O Sung'),
(DEFAULT, 'Sunlight'),
(DEFAULT, 'Haioreum'),
(DEFAULT, 'Wei Chuan'),
(DEFAULT, 'Wei Wei'),
(DEFAULT, 'Yamamori'),
(DEFAULT, 'Yamamoto'),
(DEFAULT, 'Daikoku'),
(DEFAULT, 'Master Kong'),
(DEFAULT, 'Omachi'),
(DEFAULT, 'Sura'),
(DEFAULT, 'Cap Atoom Bulan'),
(DEFAULT, 'Lishan'),
(DEFAULT, 'Mug Shot'),
(DEFAULT, 'Ohsung'),
(DEFAULT, 'Mamee'),
(DEFAULT, 'Chewy'),
(DEFAULT, 'Four Seas'),
(DEFAULT, 'Golden Mie'),
(DEFAULT, 'Gau Do'),
(DEFAULT, 'Hosoonyi'),
(DEFAULT, 'Sempio'),
(DEFAULT, 'Sarimi'),
(DEFAULT, 'Mr. Noodles'),
(DEFAULT, 'Hankow'),
(DEFAULT, 'Emart'),
(DEFAULT, 'SuperMi'),
(DEFAULT, 'Acecook'),
(DEFAULT, 'Kim''s Bowl'),
(DEFAULT, 'ABC'),
(DEFAULT, 'Chencun'),
(DEFAULT, 'Seven-Eleven'),
(DEFAULT, 'CJ CheilJedang'),
(DEFAULT, 'Dongwon'),
(DEFAULT, 'Fuji Mengyo'),
(DEFAULT, 'Song Hak'),
(DEFAULT, 'Han''s South Korea'),
(DEFAULT, 'Yamachan'),
(DEFAULT, 'FMF'),
(DEFAULT, 'Daddy'),
(DEFAULT, 'Ko-Lee'),
(DEFAULT, 'Amino'),
(DEFAULT, 'Right Foods'),
(DEFAULT, 'Trident'),
(DEFAULT, 'Sakurai Foods'),
(DEFAULT, 'Springlife'),
(DEFAULT, 'Sun Noodle'),
(DEFAULT, 'S&S'),
(DEFAULT, 'GS25'),
(DEFAULT, 'Prima Taste'),
(DEFAULT, 'Western Family'),
(DEFAULT, 'Samyang Foods'),
(DEFAULT, 'HoMyeonDang'),
(DEFAULT, 'New Touch'),
(DEFAULT, 'A-Sha Dry Noodle'),
(DEFAULT, 'Star Anise Foods'),
(DEFAULT, 'Tasty Bite'),
(DEFAULT, 'Deshome'),
(DEFAULT, 'Sawadee'),
(DEFAULT, 'MyKuali'),
(DEFAULT, 'Amianda'),
(DEFAULT, 'Tropicana Slim'),
(DEFAULT, 'Baltix'),
(DEFAULT, 'Eat & Go'),
(DEFAULT, 'La Fonte'),
(DEFAULT, 'Maitri'),
(DEFAULT, 'Tokyo Noodle'),
(DEFAULT, 'Thai Pavilion'),
(DEFAULT, 'Nagao Noodle'),
(DEFAULT, 'GaGa'),
(DEFAULT, 'Campbell''s'),
(DEFAULT, 'Oyatsu'),
(DEFAULT, 'Tesco'),
(DEFAULT, 'Hi-Myon'),
(DEFAULT, 'Asian Thai Foods'),
(DEFAULT, 'Wu-Mu'),
(DEFAULT, 'Komforte Chockolates'),
(DEFAULT, 'Golden Wonder'),
(DEFAULT, 'Peyang'),
(DEFAULT, 'Kabuto Noodles'),
(DEFAULT, 'Tiger Tiger'),
(DEFAULT, 'Pop Bihun'),
(DEFAULT, 'Healtimie'),
(DEFAULT, 'Sainsbury''s'),
(DEFAULT, 'Sanrio'),
(DEFAULT, 'Men-Sunaoshi'),
(DEFAULT, 'Sugakiya Foods'),
(DEFAULT, 'China Best'),
(DEFAULT, 'Ruski'),
(DEFAULT, 'Nan Jie Cun'),
(DEFAULT, 'Kumamoto'),
(DEFAULT, 'Saji'),
(DEFAULT, 'Thai Choice'),
(DEFAULT, 'President'),
(DEFAULT, 'Adabi'),
(DEFAULT, 'Tokachimen Koubou'),
(DEFAULT, 'Kimura'),
(DEFAULT, 'A-One'),
(DEFAULT, 'Good Tto Leu Foods'),
(DEFAULT, 'Takamori Kosan'),
(DEFAULT, 'Sakura Noodle'),
(DEFAULT, 'Kin-Dee'),
(DEFAULT, 'Plats Du Chef'),
(DEFAULT, 'Ah Lai'),
(DEFAULT, 'Lotus Foods'),
(DEFAULT, 'Papa'),
(DEFAULT, 'Shan'),
(DEFAULT, 'Miracle Noodle'),
(DEFAULT, 'Pamana'),
(DEFAULT, 'Baixiang Noodles'),
(DEFAULT, 'Chering Chang'),
(DEFAULT, 'Hao Way'),
(DEFAULT, 'Osaka Ramen'),
(DEFAULT, 'Nanyang Chef'),
(DEFAULT, 'Thai Chef'),
(DEFAULT, 'Bamee'),
(DEFAULT, 'Mom''s Dry Noodle'),
(DEFAULT, 'ICA'),
(DEFAULT, 'Super'),
(DEFAULT, 'United'),
(DEFAULT, 'Long Jun Hang'),
(DEFAULT, 'Katoz'),
(DEFAULT, 'Ching''s Secret'),
(DEFAULT, 'Pama'),
(DEFAULT, 'Miliket'),
(DEFAULT, 'Vit''s'),
(DEFAULT, 'Paldo Vina'),
(DEFAULT, 'Unif-100'),
(DEFAULT, 'No Name'),
(DEFAULT, 'Uncle Sun'),
(DEFAULT, 'Econsave'),
(DEFAULT, 'Curry Prince'),
(DEFAULT, 'Mi E-Zee'),
(DEFAULT, 'J.J.'),
(DEFAULT, 'E-mi'),
(DEFAULT, 'CarJEN'),
(DEFAULT, 'Salam Mie'),
(DEFAULT, 'Unzen'),
(DEFAULT, 'Mitoku'),
(DEFAULT, 'The Bridge'),
(DEFAULT, 'Premiere'),
(DEFAULT, 'Azami'),
(DEFAULT, 'Cintan'),
(DEFAULT, 'One Dish Asia'),
(DEFAULT, 'New Way'),
(DEFAULT, 'MyOri'),
(DEFAULT, 'ChoripDong'),
(DEFAULT, 'Lishan Food Manufacturing'),
(DEFAULT, 'A1'),
(DEFAULT, 'Ten-In'),
(DEFAULT, 'Aroi'),
(DEFAULT, 'Wugudaochang'),
(DEFAULT, 'The Kitchen Food'),
(DEFAULT, '7 Select/Nissin'),
(DEFAULT, 'Asia Gold'),
(DEFAULT, 'Lee Fah Mee'),
(DEFAULT, 'Pirkka'),
(DEFAULT, 'Yamadai'),
(DEFAULT, 'Bonasia'),
(DEFAULT, 'Marutai'),
(DEFAULT, 'Kuriki'),
(DEFAULT, 'Thai Smile'),
(DEFAULT, 'iMee'),
(DEFAULT, 'Authentically Asian'),
(DEFAULT, 'Ishimaru'),
(DEFAULT, 'Torishi'),
(DEFAULT, 'Fujiwara'),
(DEFAULT, 'Crystal Noodle'),
(DEFAULT, 'Conimex'),
(DEFAULT, 'Koh Thai'),
(DEFAULT, 'Nakaya Shouten'),
(DEFAULT, 'Sichuan Baijia'),
(DEFAULT, 'Tseng Noodles'),
(DEFAULT, 'Forest Noodles'),
(DEFAULT, 'Seven & I'),
(DEFAULT, 'Daraz'),
(DEFAULT, 'IbuRamen'),
(DEFAULT, 'Itsuki'),
(DEFAULT, 'MAMA'),
(DEFAULT, 'Prima'),
(DEFAULT, 'Higashimaru'),
(DEFAULT, 'Mie Sedaap'),
(DEFAULT, 'Love Cook'),
(DEFAULT, 'Tokushima Seifun'),
(DEFAULT, 'Suimin'),
(DEFAULT, 'Great Value'),
(DEFAULT, 'Oni Hot Pot'),
(DEFAULT, 'E-Zee'),
(DEFAULT, 'Kang Shi Fu'),
(DEFAULT, 'Urban Noodle'),
(DEFAULT, 'Singa-Me'),
(DEFAULT, 'Chaudhary''s Wai Wai'),
(DEFAULT, 'Fantastic'),
(DEFAULT, 'Migawon'),
(DEFAULT, 'ORee Garden'),
(DEFAULT, 'Zow Zow'),
(DEFAULT, 'Sanpo'),
(DEFAULT, 'Roland'),
(DEFAULT, 'Weh Lih'),
(DEFAULT, '7 Select'),
(DEFAULT, 'Happy Family'),
(DEFAULT, 'Thien Houng Foods'),
(DEFAULT, 'Dream Kitchen'),
(DEFAULT, 'Jingqi'),
(DEFAULT, 'La Moderna'),
(DEFAULT, 'President Rice'),
(DEFAULT, 'Choumama'),
(DEFAULT, 'Nyor Nyar'),
(DEFAULT, 'Mr. Lee''s Noodles'),
(DEFAULT, 'Morre'),
(DEFAULT, 'KOKA'),
(DEFAULT, 'Nagatanien'),
(DEFAULT, 'Goku-Uma'),
(DEFAULT, 'Farmer''s Heart'),
(DEFAULT, 'Unif Tung-I'),
(DEFAULT, 'Chuan Wei Wang'),
(DEFAULT, 'Ajinatori'),
(DEFAULT, 'Pran'),
(DEFAULT, 'Xiao Ban Mian'),
(DEFAULT, 'Happy Cook'),
(DEFAULT, 'Ogasawara'),
(DEFAULT, 'Qin Zong'),
(DEFAULT, 'Patanjali'),
(DEFAULT, 'Ripe''n''Dry'),
(DEFAULT, '1 To 3 Noodles'),
(DEFAULT, 'Liu Quan'),
(DEFAULT, 'World O'' Noodle'),
(DEFAULT, 'Sichuan Guangyou'),
(DEFAULT, 'Hua Feng'),
(DEFAULT, 'Liang Cheng Mai'),
(DEFAULT, 'Just Way'),
(DEFAULT, 'Mama Pat''s'),
(DEFAULT, 'Xiuhe'),
(DEFAULT, 'Dr. McDougall''s'),
(DEFAULT, 'TTL'),
(DEFAULT, 'Mum Ngon'),
(DEFAULT, 'Daifuku'),
(DEFAULT, 'GGE'),
(DEFAULT, 'Kiki Noodle'),
(DEFAULT, 'The Ramen Rater Select'),
(DEFAULT, 'Pringles'),
(DEFAULT, 'Ikeda Shoku'),
(DEFAULT, 'Samurai Ramen'),
(DEFAULT, 'Guava Story'),
(DEFAULT, 'Takamori'),
(DEFAULT, 'Sokensha'),
(DEFAULT, 'Lele'),
(DEFAULT, 'Lipton'),
(DEFAULT, 'Yum-Mie'),
(DEFAULT, 'Jackpot Teriyaki'),
(DEFAULT, 'TRDP'),
(DEFAULT, 'Tao Kae Noi'),
(DEFAULT, 'Blount'),
(DEFAULT, 'Sunfeast'),
(DEFAULT, 'TableMark'),
(DEFAULT, 'Tseng Noodle'),
(DEFAULT, 'Nona Lim'),
(DEFAULT, 'Gookmul'),
(DEFAULT, 'Isoyama Shoji'),
(DEFAULT, 'Nanoblock'),
(DEFAULT, 'Happy Noodle'),
(DEFAULT, 'Alhami'),
(DEFAULT, 'Mikka'),
(DEFAULT, 'Hokkaido Ramen Santouka'),
(DEFAULT, 'Village Vanguard'),
(DEFAULT, 'Qicaiyuan'),
(DEFAULT, 'Chuanbei'),
(DEFAULT, 'Kenko Foods'),
(DEFAULT, 'Ichiran Ramen'),
(DEFAULT, 'My Friend'),
(DEFAULT, 'Qinsheng'),
(DEFAULT, 'Banzai'),
(DEFAULT, 'Yumei'),
(DEFAULT, 'No Brand'),
(DEFAULT, 'Jinbo Selection'),
(DEFAULT, 'Kaset'),
(DEFAULT, 'Meimen'),
(DEFAULT, 'Red Chef'),
(DEFAULT, 'Ped Chef'),
(DEFAULT, 'Island Foods'),
(DEFAULT, 'LeeZen'),
(DEFAULT, 'Mr. Noodle'),
(DEFAULT, 'Mike''s Mighty Good Craft Ramen'),
(DEFAULT, 'World O Noodle'),
(DEFAULT, 'Little Couples Q Noodle'),
(DEFAULT, 'Liangchengmei'),
(DEFAULT, 'Myramen'),
(DEFAULT, 'Da Long Yi'),
(DEFAULT, 'Shanjinshan'),
(DEFAULT, 'Kizuki Ramen & Izakaya'),
(DEFAULT, 'Shibu Ramen'),
(DEFAULT, 'Chongqing Suanlabao Food Co., Ltd.'),
(DEFAULT, 'nunu'),
(DEFAULT, 'Miandom'),
(DEFAULT, 'Taihodien Restaurant'),
(DEFAULT, 'Three Meters Noodles'),
(DEFAULT, 'Sugakiya'),
(DEFAULT, 'Neko'),
(DEFAULT, 'Fox'),
(DEFAULT, 'Big Bon'),
(DEFAULT, 'Saikebon'),
(DEFAULT, 'Best Wok'),
(DEFAULT, 'Kiki'),
(DEFAULT, 'Sunaoshi'),
(DEFAULT, 'Lemonilo'),
(DEFAULT, 'A-Sha'),
(DEFAULT, 'Soup Daren'),
(DEFAULT, 'Buitoni'),
(DEFAULT, 'Tapatio'),
(DEFAULT, 'San-Iku'),
(DEFAULT, 'Lien Ying'),
(DEFAULT, 'Rollton'),
(DEFAULT, 'Rooster'),
(DEFAULT, 'Canton'),
(DEFAULT, 'Ajinomoto'),
(DEFAULT, 'Nissin-Miojo'),
(DEFAULT, 'Bowlfull'),
(DEFAULT, 'Picnic'),
(DEFAULT, 'Mibena'),
(DEFAULT, 'Nissin Miojo'),
(DEFAULT, 'Peyoung'),
(DEFAULT, 'Kinchan'),
(DEFAULT, 'Vite Ramen'),
(DEFAULT, 'Panco'),
(DEFAULT, 'Trader Joe''s'),
(DEFAULT, 'Fantastic Noodles'),
(DEFAULT, 'Chitato'),
(DEFAULT, 'Mamee-Shinsegae'),
(DEFAULT, 'Jinya Ramen Bar'),
(DEFAULT, 'COCO 2.0'),
(DEFAULT, 'Fu Chung'),
(DEFAULT, 'Mivina'),
(DEFAULT, 'Burung Layang Terbang'),
(DEFAULT, 'Way Premium Foods'),
(DEFAULT, 'Lau Liu Tou'),
(DEFAULT, 'Neo~Essence'),
(DEFAULT, 'Yi Lai Shuen'),
(DEFAULT, 'Double Mountain'),
(DEFAULT, 'Culley''s'),
(DEFAULT, 'Suraj'),
(DEFAULT, 'Luosiking'),
(DEFAULT, 'Mamee Shinsegae'),
(DEFAULT, 'Micoem'),
(DEFAULT, 'Fukumen'),
(DEFAULT, 'Quero'),
(DEFAULT, 'Maison de Coree'),
(DEFAULT, 'Hakubaku'),
(DEFAULT, 'Jinmailang'),
(DEFAULT, 'TIEasy'),
(DEFAULT, 'Simply Asia'),
(DEFAULT, 'Mazendo'),
(DEFAULT, 'Mamee / Shinsegae'),
(DEFAULT, 'Samlip'),
(DEFAULT, 'Tian Ling Ling'),
(DEFAULT, 'Easybab'),
(DEFAULT, 'Atomy'),
(DEFAULT, 'Lau Liu tou'),
(DEFAULT, 'Mykuali'),
(DEFAULT, 'Nakaki'),
(DEFAULT, 'Hite'),
(DEFAULT, 'Ebisoba Ichigen'),
(DEFAULT, 'Cigala'),
(DEFAULT, 'Mitukura'),
(DEFAULT, 'Hokkaido Furano Ramen'),
(DEFAULT, 'Shin Horng'),
(DEFAULT, 'Ramen Hero'),
(DEFAULT, 'Kuro Tetsuya'),
(DEFAULT, 'Kikusui'),
(DEFAULT, 'Aji-no-men'),
(DEFAULT, 'FitMee'),
(DEFAULT, 'Hide Chan'),
(DEFAULT, 'Haogemen'),
(DEFAULT, 'Palkin'),
(DEFAULT, 'EDO Pack'),
(DEFAULT, 'O''taste'),
(DEFAULT, 'Pan Mee'),
(DEFAULT, 'Kubota'),
(DEFAULT, 'Jinanbo'),
(DEFAULT, 'Yatekomo'),
(DEFAULT, '7-Eleven / Nissin'),
(DEFAULT, 'Chil Kab Farm Products'),
(DEFAULT, 'Himawari-Shokuhin'),
(DEFAULT, 'Teishi'),
(DEFAULT, 'Zombear'),
(DEFAULT, 'Jongga'),
(DEFAULT, 'Tabate'),
(DEFAULT, 'Chef Nic''s Noodles'),
(DEFAULT, 'Three Meters'),
(DEFAULT, 'Shuang Ren Hsu'),
(DEFAULT, 'Nissin '),
(DEFAULT, 'LMF'),
(DEFAULT, 'Nasoya'),
(DEFAULT, 'Qi Shi Liu Ren'),
(DEFAULT, 'Shun Savory'),
(DEFAULT, 'Hikari Miso'),
(DEFAULT, 'Yibin'),
(DEFAULT, 'Eight Field'),
(DEFAULT, 'Street Noodles'),
(DEFAULT, 'Taim'),
(DEFAULT, 'One Culture Foods'),
(DEFAULT, 'Base Foods'),
(DEFAULT, 'Samurai'),
(DEFAULT, 'Taihodien'),
(DEFAULT, 'Seven & i'),
(DEFAULT, 'Young Poong'),
(DEFAULT, 'Daisho'),
(DEFAULT, 'Mr. Min'),
(DEFAULT, 'Little Couples');
