CREATE TABLE countries (
  id SERIAL PRIMARY KEY,
  country TEXT UNIQUE NOT NULL
);

INSERT INTO countries
VALUES
(DEFAULT, 'United States'),
(DEFAULT, 'Thailand'),
(DEFAULT, 'Vietnam'),
(DEFAULT, 'Taiwan'),
(DEFAULT, 'South Korea'),
(DEFAULT, 'Japan'),
(DEFAULT, 'Philippines'),
(DEFAULT, 'Singapore'),
(DEFAULT, 'Indonesia'),
(DEFAULT, 'China'),
(DEFAULT, 'Hong Kong'),
(DEFAULT, 'India'),
(DEFAULT, 'Malaysia'),
(DEFAULT, 'Canada'),
(DEFAULT, 'Pakistan'),
(DEFAULT, 'Holland'),
(DEFAULT, 'UK'),
(DEFAULT, 'Dubai'),
(DEFAULT, 'Fiji'),
(DEFAULT, 'Poland'),
(DEFAULT, 'Australia'),
(DEFAULT, 'Estonia'),
(DEFAULT, 'Nepal'),
(DEFAULT, 'Colombia'),
(DEFAULT, 'Germany'),
(DEFAULT, 'Sweden'),
(DEFAULT, 'Bangladesh'),
(DEFAULT, 'Myanmar'),
(DEFAULT, 'Sarawak'),
(DEFAULT, 'Hungary'),
(DEFAULT, 'Finland'),
(DEFAULT, 'Cambodia'),
(DEFAULT, 'Netherlands'),
(DEFAULT, 'Brazil'),
(DEFAULT, 'Mexico'),
(DEFAULT, 'Nigeria'),
(DEFAULT, 'Ghana'),
(DEFAULT, 'Phlippines'),
(DEFAULT, 'USA'),
(DEFAULT, 'Russia'),
(DEFAULT, 'Italy'),
(DEFAULT, 'Ukraine'),
(DEFAULT, 'New Zealand'),
(DEFAULT, 'France'),
(DEFAULT, 'United Kingdom'),
(DEFAULT, 'Portugal'),
(DEFAULT, 'Peru'),
(DEFAULT, 'Spain'),
(DEFAULT, 'Israel'),
(DEFAULT, 'Souh Korea');
